### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by robrecord** [zokugun/vscode-sync-settings#12]
I get the following error when I try to upload settings:

```Sync Settings: TypeError: Cannot read property 'id' of undefined```

My settings:

```yml
profile: main
repository:
  type: file
  path: ~/Code/vscode-settings
```
