### ISSUE TITLE
Hostname generator does not work

### ISSUE THREAD

**Issue by vfauth** [zokugun/vscode-sync-settings#26]
Hi,
Thank you for this awesome extension!

I have a small issue with the hostname generator, which seem to always return an empty string. Here is my config.json:
```json
    "syncSettings.gitInitMessage": "{{profile}}: init -- {{now|date:iso}} - {{hostname}}",
    "syncSettings.gitUpdateMessage": "{{profile}}: update -- {{now|date:iso}} - {{hostname}}",
    "syncSettings.hostname": "T{{hostname}}",
```
    
 And my settings.yml:
```yaml
# selected profile, required
profile: main
# sync on remote git
repository:
  type: git
  url: ssh://git@XXX/vs-code-sync.git
  branch: master
```

I already restarted VS Code, which seems to be required for the new settings to be changed, but my commit names are still **`main: update -- 2022-08-17T09:47:55.410Z -`**

It is as if the settings.yml still defined an empty hostname. Any idea?
