### ISSUE TITLE
automatic sync after time

### ISSUE THREAD

**Issue by Tealk** [zokugun/vscode-sync-settings#28]
Currently you always have to remember to back up your configuration, it would be nice if you could set a time that it is backed up e.g. 1 time per day.

**Comment by daiyam** [comment]
It's an interesting idea.

**Comment by daiyam** [comment]
I was thinking about something like this:
```
crons:
- at: 0 9 * * *
  run: syncSettings.download
- at: 0 17 * * *
  run: syncSettings.upload
```

But then, it isn't limited to just syncing the settings. It becomes outside the scope of this extension.

So you might use either solution:
- https://marketplace.visualstudio.com/items?itemName=mkloubert.vs-cron
- https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools
