### ISSUE TITLE
How to use local git configuration for remote git sync?

### ISSUE THREAD

**Issue by matusf** [zokugun/vscode-sync-settings#29]
Hello, I'd like to use local git config (not global), because I have multiple "git profiles" and I always want to choose which one to use (with default/global config I'll forget about it and mistakenly use wrong "profile"). Is there a way to manually set the email and name? If I knew where is the git directory, I could `cd` there and run `git config`, but I do not know where it is located. 

![image](https://user-images.githubusercontent.com/18228995/190129126-28377288-66fa-4d1f-84b1-5afea21fc8e1.png)

**Comment by daiyam** [comment]
The local git is located where you have set the setting `path`.

For example:
```yaml
# sync on local git
repository:
  type: git
  # path of the local git repository to sync with, required
  path: ~/Development/settings
  # branch to sync on, optional (set to `master` by default)
  branch: master
```

Use `> Sync Settings: Open the repository settings` to open the settings of the extension

From my example, if `~/Development/settings` isn't already a git repository, it will create as such.
Then, you can manage it as a regular git repository.
https://support.atlassian.com/bitbucket-cloud/docs/configure-your-dvcs-username-for-commits/
