### ISSUE TITLE
Feature request: Allow conditionals in extensions.yml files

### ISSUE THREAD

**Issue by binaryben** [zokugun/vscode-sync-settings#31]
Thanks for this project! Glad to have my settings and extensions being synced in my standard dotfiles repo!

I find myself using both VSCode and Codium at times. Some extensions are only available on one or the other (MS Remote tools), and some have mismatched IDs (eg. MJML, Theme by file). Allowing conditionals in the `extensions.yml` files would mean I don't have to manage seperate profiles for each.

I suspect this could be useful for OS specific extensions as well.

**Comment by daiyam** [comment]
Hi, I see that you are already using profiles for different languages. So adding a different set by editors will be quite difficult.

**Comment by binaryben** [comment]
Indeed, hence the request for [conditionals similar to what is available in the `settings.json` files](https://github.com/zokugun/vscode-sync-settings#jsonc-attributes) in the `extension.yml` files of each profile.

I'm hoping since YAML is related to JSON, it's possible. But an alternative could be to extend the YAML extension definition itself. For example:

```yaml
enabled:
  - id: GitHub.codespaces
    uuid: 4023d3e5-c840-4cdd-8b54-51c77548aa3f
    editor: visual studio code
  - id: sebsojeda.vscode-apple-music
    uuid: 48c4d108-0dd6-4404-8c20-c6f62c59950c
    os: mac
```
