### ISSUE TITLE
How to use several git configs on one machine and be able to separately sync settings to corresponding github account settings repo?

### ISSUE THREAD

**Issue by d3lv1n** [zokugun/vscode-sync-settings#54]
Hi.

For example:

I have `$HOME/.gitconfig`:

```
[includeIf "gitdir:~/personal/"]
  path = ~/.gitconfig-personal
[includeIf "gitdir:~/work/"]
  path = ~/.gitconfig-work
```

`$HOME/.gitconfig-personal`:

```
[user]
  name = personal_user
  email = personal_email
```

And `$HOME/.gitconfig-work`:

```
[user]
  name = work_user
  email = work_email
```

I also have personal and work Sync Settings profiles:

`settings.yml` for personal profile:

```
hostname: ""
profile: personal
repository:
  type: git
  url: https://github.com/<personal-username>/editor-settings.git
  branch: main
```

And  `settings.yml` for work profile:

```
hostname: ""
profile: work
repository:
  type: git
  url: https://github.com/<work-username>/editor-settings.git
  branch: main
```

And when I'm switched to the work Sync Settings profile and using `Sync Settings: Upload (user -> repository)` command in VSCodium, I want to push those work settings to my work github account only and of course I want my work git name and email were used from the corresponding git config.

Of course, this setup does not work, it is more for what I want to achieve. Is there a way to achieve this somehow not necessarily having the exact setup?
