### ISSUE TITLE
Port for repository

### ISSUE THREAD

**Issue by donkeyDau** [zokugun/vscode-sync-settings#63]
I've tried to use the `git` type:

```yaml
# sync on remote git
repository:
  type: git
  # url of the remote git repository to sync with, required
  url: git@my.git.instance:custom_port/vscode-settings.git
  # branch to sync on, optional (set to `master` by default)
  branch: main
```

But it does not work. On uploading I get the error that the repo cannot be initialized. The second error is a git connection error stating that the repo cannot be reached on port 22. But in the settings I've given the custom port in the `url` but it seems not to be followed.

![Unbenannt](https://github.com/zokugun/vscode-sync-settings/assets/17231336/ee9bd137-62df-4038-ac06-f55c1f0f1834)

**Comment by daiyam** [comment]
It uses your system `git` so you have to make sure that it has read/write access to your repository.

**Comment by daiyam** [comment]
Can you give the logs in `View` / `Output` / `Sync Settings`?

**Comment by donkeyDau** [comment]
My bad: I had to give a `ssh://` prefix. So in total it looks like:

```
# sync on remote git
repository:
  type: git
  # url of the remote git repository to sync with, required
  url: ssh://git@my.git.instance:custom_port/vscode-settings.git
  # branch to sync on, optional (set to `master` by default)
  branch: main
  ```
