### ISSUE TITLE
Does this support code-server?

### ISSUE THREAD

**Issue by libook** [zokugun/vscode-sync-settings#66]
I am using [code-server](https://github.com/coder/code-server) and wish to sync settings between my code-server and Code OSS.
Currently only `extensions.yml` was uploaded from code-server.

My `settings.yml`
```
# current machine's name, optional; it can be used to filter settings or in the commit message
hostname: ""
# more details at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/hostname.md

# selected profile, required
profile: main
# repository to sync the settings with, required
repository:
  # repository's type, required (dummy: no sync)
  # type: dummy
  type: file
  # path of the local directory to sync with, required
  path: ~/Documents/Code Profiles/settings
```
