### ISSUE TITLE
SSH key

### ISSUE THREAD

**Issue by Johnymalina** [zokugun/vscode-sync-settings#74]
Hi,

iam getting auth errors using my git server. Iam running git SSH on non standart port but not having problems connect using terminal.  I also added key to ssh agent using ssh-add. Is there any way to specify path for key?
```
Sync Settings: Error: kuba@mydomain.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

```
repository:
  type: git
  url: ssh://git@mydomain.com:2224/user/code-settings.git
  branch: main
```

**Comment by daiyam** [comment]
The extension uses your system `git`.
In a terminal, test if you can connect to it with `ssh -Tv mydomain.com -p 2224`

I would recommend you to have a `Host` entry in `~/.ssh/config` for your server.
More details at https://nerderati.com/2011-03-17-simplify-your-life-with-an-ssh-config-file/

**Comment by Johnymalina** [comment]
i did all of that but the extension giving me still errors

```Sync Settings: Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
Sync Settings: The git repository can not be pulled
Sync Settings: Error: git@git.thehorde.page: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by daiyam** [comment]
Ah! Not need for `ssh://`

```
repository:
  type: git
  url: git@mydomain.com:2224/user/code-settings.git
  branch: main
```

so it can execute `git clone git@mydomain.com:2224/user/code-settings.git`
