### ISSUE TITLE
Extension does not sync anything.

### ISSUE THREAD

**Issue by bitfl0wer** [zokugun/vscode-sync-settings#77]
Platform: Linux x86-64, Fedora Workstation 41
Editor: VSCodium 1.96.4
Extension Version: 0.16.0

## The extension does not sync anything.

`/home/$user/.config/VSCodium/User/settings.json`:

```json
{
	"window.titleBarStyle": "custom",
	"window.customTitleBarVisibility": "auto",
	"window.newWindowProfile": "flori",
	"syncSettings.resources": ["settings", "extensions", "keybindings"],
	"syncSettings.gitInitMessage": "profile({{profile}}@{{hostname}}): init -- {{now|date:iso}}",
	"syncSettings.gitUpdateMessage": "profile({{profile}}@{{hostname}}): update -- {{now|date:iso}}",
	"syncSettings.keybindingsPerPlatform": false
}
```

Sync Settings settings.yml:

```yml
hostname: "starforge"
profile: flori
repository:
  type: git
  url: https://github.com/bitfl0wer/vscodium-config.git
```

**Description:** When specifying "`syncSettings.resources`", the extension does not sync anything. When this setting is not present, the extension does sync some things; however, it does not sync all the things I'd like it to. It seems like setting the `syncSettings.resources` parameters breaks syncing. Below are log outputs of trying to sync (upload) without this parameter present, then trying to sync (upload) after setting the parameter:

```
[info] serialize to: /home/star/.config/VSCodium/User/globalStorage/zokugun.sync-settings/repository
[info] serialize extensions
[info] serialize snippets
[info] serialize UI state
[info] serialize keybindings
[info] serialize settings
[info] serialize done
[info] commit: profile(flori@starforge): update -- 2025-01-26T11:39:43.346Z
[info] push to remote
[info] push done
---vvv-parameter present---
[info] serialize to: /home/star/.config/VSCodium/User/globalStorage/zokugun.sync-settings/repository
[info] serialize done | < nothing was serialized?
[info] commit: profile(flori@starforge): update -- 2025-01-26T11:44:04.025Z
[info] push to remote
[info] push done
```

**Comment by daiyam** [comment]
I've just retested. it's working on my machine.

- After an upload, can you try the command `> Sync Settings: Reveal the profile in the file explorer`.
  You should see a `data` directory
- `git push` would need to work with `https://github.com/bitfl0wer/vscodium-config.git`.
  I would recommend to use the ssh url `git@github.com:bitfl0wer/vscodium-settings.git`

**Comment by bitfl0wer** [comment]
> After an upload, can you try the command > Sync Settings: Reveal the profile in the file explorer.
You should see a data directory

A recursive `tree` of that path shows:

```
tree -aR
.
├── data
├── .gitkeep
└── .sync.yml

2 directories, 2 files
```

> git push would need to work with https://github.com/bitfl0wer/vscodium-config.git.

It does work, even using HTTPS instead of SSH. As mentioned, syncing of *some* resources works, if the parameter is not present. The extension can push to the GitHub repository just fine.

**Comment by daiyam** [comment]
I did test with `"syncSettings.resources": ["settings", "extensions", "keybindings"],`

I don't understand why you have the issue. I copy pasted your settings...
I will add a log for the read `syncSettings.resources` to verify its value is correctly read.

**Comment by gaotako** [comment]
I have a similar issue of incomplete syncing when using VSCode server on an AWS SageMaker instance (For VS Code on local machine, it is fine), here is the editor version info:
```
code-server: v4.16.1
Code: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-31T17:15:21.760Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
```
The issue is that for either git remote (SSH) or git local sync, only extensions are synced, for settings and other staff, they are not synced regardless of `syncSettings.resources`, here is a local sync test config:
```
hostname: ""
profile: main
#:||repository:
#:||    type: git
#:||    # if on developement instance, use SSH (the first) instead of HTTPS (the second, default)
#:||    url: git@github.com:gaotako/CodeServerSyncSettings.git
#:||    # url: https://github.com/gaotako/CodeServerSyncSettings.git
#:||    branch: main
repository:
    type: git
    path: ~/SageMaker/RuntimeCommand/src/CodeServerSyncSettings
    branch: main
```
And here is the directory tree after upload:
```
$ ls -R ~/SageMaker/RuntimeCommand/src/CodeServerSyncSettings
/home/ec2-user/SageMaker/RuntimeCommand/src/CodeServerSyncSettings:
profiles

/home/ec2-user/SageMaker/RuntimeCommand/src/CodeServerSyncSettings/profiles:
main

/home/ec2-user/SageMaker/RuntimeCommand/src/CodeServerSyncSettings/profiles/main:
data

/home/ec2-user/SageMaker/RuntimeCommand/src/CodeServerSyncSettings/profiles/main/data:
extensions.yml
```

P.S. On remote instance, I use my customized XDG_HOME settings, thus some files are not in their default location, not sure if this will have any influence.
